namespace :test_task do
  p "TASK GENERATED BY RAILS GENERATOR"

  task :only_run_when_told do
    puts "TRAVIS ONLY RUNS THIS TASK WHEN TOLD"
  end

  task :do_not_run do
    puts "TRAVIS SHOULD NOT EXECUTE THIS TASK"
  end

  task :heroku_rake_test do
    puts "THIS TASK SHOULD ONLY EXECUTE IN HEROKU"
    puts "IF YOU SEE THIS MESSAGE ANYWHERE OUTSIDE HEROKU LOGS"
    puts "GET IN TOUCH WITH YOUR SITE ADMIN"
  end
end
