namespace :test_task do
  desc "test task to run before adding serious tasks"
  task :some_task do
    p "TASK GENERATED BY RAILS GENERATOR"
  end

  desc "another test task to test execution of namespace"
  task :second_task do
    p "RAKE EXECUTES SECOND TASK IN TEST NAMESPACE"
  end
end
