namespace :test_task do
    p "TASK GENERATED BY RAILS GENERATOR"
    var score = ["A", "B", "C", "F"].sample
    var add = ["+", "-", ""].sample
    p "Rake gives you a #{score} #{add} for your build"
  end

