require: rubocop-rails

AllCops:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/posts_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'bin/setup'
    - 'bin/update'
    - 'config/application.rb'
    - 'db/migrate/20170526114520_create_posts.rb'
    - 'spec/controllers/post_controllers_spec.rb'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'config/environments/production.rb'
    - 'config/initializers/devise.rb'
    - 'spec/features/user_must_sign_in_spec.rb'
    - 'db/migrate/20200213100303_devise_create_users.rb'
    - 'Gemfile'


# Layout/LineLength:
#   Enabled: false

Style/Documentation:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false
