 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/comment_likes", type: :request do
  # CommentLike. As you add validations to CommentLike, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CommentLike.create! valid_attributes
      get comment_likes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      comment_like = CommentLike.create! valid_attributes
      get comment_like_url(comment_like)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_comment_like_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      comment_like = CommentLike.create! valid_attributes
      get edit_comment_like_url(comment_like)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CommentLike" do
        expect {
          post comment_likes_url, params: { comment_like: valid_attributes }
        }.to change(CommentLike, :count).by(1)
      end

      it "redirects to the created comment_like" do
        post comment_likes_url, params: { comment_like: valid_attributes }
        expect(response).to redirect_to(comment_like_url(CommentLike.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CommentLike" do
        expect {
          post comment_likes_url, params: { comment_like: invalid_attributes }
        }.to change(CommentLike, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post comment_likes_url, params: { comment_like: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested comment_like" do
        comment_like = CommentLike.create! valid_attributes
        patch comment_like_url(comment_like), params: { comment_like: new_attributes }
        comment_like.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the comment_like" do
        comment_like = CommentLike.create! valid_attributes
        patch comment_like_url(comment_like), params: { comment_like: new_attributes }
        comment_like.reload
        expect(response).to redirect_to(comment_like_url(comment_like))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        comment_like = CommentLike.create! valid_attributes
        patch comment_like_url(comment_like), params: { comment_like: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested comment_like" do
      comment_like = CommentLike.create! valid_attributes
      expect {
        delete comment_like_url(comment_like)
      }.to change(CommentLike, :count).by(-1)
    end

    it "redirects to the comment_likes list" do
      comment_like = CommentLike.create! valid_attributes
      delete comment_like_url(comment_like)
      expect(response).to redirect_to(comment_likes_url)
    end
  end
end
