# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator

RSpec.describe AlbumsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Album. As you add validations to Album, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlbumsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'returns a success response' do
      album = Album.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      album = Album.create! valid_attributes
      get :show, params: { id: album.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      album = Album.create! valid_attributes
      get :edit, params: { id: album.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Album' do
        expect do
          post :create, params: { album: valid_attributes }, session: valid_session
        end.to change(Album, :count).by(1)
      end

      it 'redirects to the created album' do
        post :create, params: { album: valid_attributes }, session: valid_session
        expect(response).to redirect_to(Album.last)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { album: invalid_attributes }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested album' do
        album = Album.create! valid_attributes
        put :update, params: { id: album.to_param, album: new_attributes }, session: valid_session
        album.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the album' do
        album = Album.create! valid_attributes
        put :update, params: { id: album.to_param, album: valid_attributes }, session: valid_session
        expect(response).to redirect_to(album)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        album = Album.create! valid_attributes
        put :update, params: { id: album.to_param, album: invalid_attributes }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested album' do
      album = Album.create! valid_attributes
      expect do
        delete :destroy, params: { id: album.to_param }, session: valid_session
      end.to change(Album, :count).by(-1)
    end

    it 'redirects to the albums list' do
      album = Album.create! valid_attributes
      delete :destroy, params: { id: album.to_param }, session: valid_session
      expect(response).to redirect_to(albums_url)
    end
  end
end
