require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe LikesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Like. As you add validations to Like, be sure to
  # adjust the attributes here as well.
  let(:user) { User.first }

  let(:valid_attributes) {
    { post_id: user.posts.first.id
    }
  }

  let(:invalid_attributes) {
    { user_id: 0,
      post_id: 0
    }
  }

  before(:each) do
    sign_in User.find_by_id(1)
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Like" do
        expect {
          post :create, params: valid_attributes
        }.to change(Like, :count).by(1)
      end

      it "creates only one Like" do
        post :create, params: valid_attributes
        expect {
          post :create, params: valid_attributes
        }.to change(Like, :count).by(0)
      end

      it "redirects to the posts index" do
        post :create, params: valid_attributes
        expect(response).to redirect_to(posts_path)
      end
    end

    context "with invalid params" do
      xit "returns a success response (i.e. to display the 'new')" do
        post :create, params: { like: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    xit "destroys the requested like" do
      like = Like.create! valid_attributes
      expect {
        delete :destroy, params: { id: like.to_param }
      }.to change(Like, :count).by(-1)
    end

    xit "redirects to the posts list" do
      like = Like.create! valid_attributes
      delete :destroy, params: { id: like.to_param }
      expect(response).to redirect_to(posts_url)
    end
  end

end
